//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebApp.WebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Service.org/", ConfigurationName="WebServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name Password from namespace http://Service.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/Verification", ReplyAction="*")]
        EmployeeWebApp.WebServiceReference.VerificationResponse Verification(EmployeeWebApp.WebServiceReference.VerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/Verification", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeWebApp.WebServiceReference.VerificationResponse> VerificationAsync(EmployeeWebApp.WebServiceReference.VerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/GetID", ReplyAction="*")]
        long GetID(long StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/GetID", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetIDAsync(long StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/OutstandingReq", ReplyAction="*")]
        void OutstandingReq();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/OutstandingReq", ReplyAction="*")]
        System.Threading.Tasks.Task OutstandingReqAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/ConfirmedReq", ReplyAction="*")]
        void ConfirmedReq();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/ConfirmedReq", ReplyAction="*")]
        System.Threading.Tasks.Task ConfirmedReqAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/EmployeeHolidayStatus", ReplyAction="*")]
        void EmployeeHolidayStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/EmployeeHolidayStatus", ReplyAction="*")]
        System.Threading.Tasks.Task EmployeeHolidayStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/SubmitHolidayReq", ReplyAction="*")]
        bool SubmitHolidayReq(System.DateTime startH, System.DateTime endH, long StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.org/SubmitHolidayReq", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SubmitHolidayReqAsync(System.DateTime startH, System.DateTime endH, long StaffID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Verification", Namespace="http://Service.org/", Order=0)]
        public EmployeeWebApp.WebServiceReference.VerificationRequestBody Body;
        
        public VerificationRequest() {
        }
        
        public VerificationRequest(EmployeeWebApp.WebServiceReference.VerificationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Service.org/")]
    public partial class VerificationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int StaffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public VerificationRequestBody() {
        }
        
        public VerificationRequestBody(int StaffID, string Password) {
            this.StaffID = StaffID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificationResponse", Namespace="http://Service.org/", Order=0)]
        public EmployeeWebApp.WebServiceReference.VerificationResponseBody Body;
        
        public VerificationResponse() {
        }
        
        public VerificationResponse(EmployeeWebApp.WebServiceReference.VerificationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Service.org/")]
    public partial class VerificationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificationResult;
        
        public VerificationResponseBody() {
        }
        
        public VerificationResponseBody(bool VerificationResult) {
            this.VerificationResult = VerificationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : EmployeeWebApp.WebServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<EmployeeWebApp.WebServiceReference.WebServiceSoap>, EmployeeWebApp.WebServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeWebApp.WebServiceReference.VerificationResponse EmployeeWebApp.WebServiceReference.WebServiceSoap.Verification(EmployeeWebApp.WebServiceReference.VerificationRequest request) {
            return base.Channel.Verification(request);
        }
        
        public bool Verification(int StaffID, string Password) {
            EmployeeWebApp.WebServiceReference.VerificationRequest inValue = new EmployeeWebApp.WebServiceReference.VerificationRequest();
            inValue.Body = new EmployeeWebApp.WebServiceReference.VerificationRequestBody();
            inValue.Body.StaffID = StaffID;
            inValue.Body.Password = Password;
            EmployeeWebApp.WebServiceReference.VerificationResponse retVal = ((EmployeeWebApp.WebServiceReference.WebServiceSoap)(this)).Verification(inValue);
            return retVal.Body.VerificationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeWebApp.WebServiceReference.VerificationResponse> EmployeeWebApp.WebServiceReference.WebServiceSoap.VerificationAsync(EmployeeWebApp.WebServiceReference.VerificationRequest request) {
            return base.Channel.VerificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebApp.WebServiceReference.VerificationResponse> VerificationAsync(int StaffID, string Password) {
            EmployeeWebApp.WebServiceReference.VerificationRequest inValue = new EmployeeWebApp.WebServiceReference.VerificationRequest();
            inValue.Body = new EmployeeWebApp.WebServiceReference.VerificationRequestBody();
            inValue.Body.StaffID = StaffID;
            inValue.Body.Password = Password;
            return ((EmployeeWebApp.WebServiceReference.WebServiceSoap)(this)).VerificationAsync(inValue);
        }
        
        public long GetID(long StaffID) {
            return base.Channel.GetID(StaffID);
        }
        
        public System.Threading.Tasks.Task<long> GetIDAsync(long StaffID) {
            return base.Channel.GetIDAsync(StaffID);
        }
        
        public void OutstandingReq() {
            base.Channel.OutstandingReq();
        }
        
        public System.Threading.Tasks.Task OutstandingReqAsync() {
            return base.Channel.OutstandingReqAsync();
        }
        
        public void ConfirmedReq() {
            base.Channel.ConfirmedReq();
        }
        
        public System.Threading.Tasks.Task ConfirmedReqAsync() {
            return base.Channel.ConfirmedReqAsync();
        }
        
        public void EmployeeHolidayStatus() {
            base.Channel.EmployeeHolidayStatus();
        }
        
        public System.Threading.Tasks.Task EmployeeHolidayStatusAsync() {
            return base.Channel.EmployeeHolidayStatusAsync();
        }
        
        public bool SubmitHolidayReq(System.DateTime startH, System.DateTime endH, long StaffID) {
            return base.Channel.SubmitHolidayReq(startH, endH, StaffID);
        }
        
        public System.Threading.Tasks.Task<bool> SubmitHolidayReqAsync(System.DateTime startH, System.DateTime endH, long StaffID) {
            return base.Channel.SubmitHolidayReqAsync(startH, endH, StaffID);
        }
    }
}
