//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebApp.LoginReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetID", ReplyAction="*")]
        long GetID(long StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetID", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetIDAsync(long StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OutstandingReq", ReplyAction="*")]
        void OutstandingReq();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OutstandingReq", ReplyAction="*")]
        System.Threading.Tasks.Task OutstandingReqAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmedReq", ReplyAction="*")]
        void ConfirmedReq();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmedReq", ReplyAction="*")]
        System.Threading.Tasks.Task ConfirmedReqAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeHolidayStatus", ReplyAction="*")]
        void EmployeeHolidayStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeHolidayStatus", ReplyAction="*")]
        System.Threading.Tasks.Task EmployeeHolidayStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitHolidayReq", ReplyAction="*")]
        bool SubmitHolidayReq(System.DateTime startH, System.DateTime endH, long StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitHolidayReq", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SubmitHolidayReqAsync(System.DateTime startH, System.DateTime endH, long StaffID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : EmployeeWebApp.LoginReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<EmployeeWebApp.LoginReference.WebServiceSoap>, EmployeeWebApp.LoginReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long GetID(long StaffID) {
            return base.Channel.GetID(StaffID);
        }
        
        public System.Threading.Tasks.Task<long> GetIDAsync(long StaffID) {
            return base.Channel.GetIDAsync(StaffID);
        }
        
        public void OutstandingReq() {
            base.Channel.OutstandingReq();
        }
        
        public System.Threading.Tasks.Task OutstandingReqAsync() {
            return base.Channel.OutstandingReqAsync();
        }
        
        public void ConfirmedReq() {
            base.Channel.ConfirmedReq();
        }
        
        public System.Threading.Tasks.Task ConfirmedReqAsync() {
            return base.Channel.ConfirmedReqAsync();
        }
        
        public void EmployeeHolidayStatus() {
            base.Channel.EmployeeHolidayStatus();
        }
        
        public System.Threading.Tasks.Task EmployeeHolidayStatusAsync() {
            return base.Channel.EmployeeHolidayStatusAsync();
        }
        
        public bool SubmitHolidayReq(System.DateTime startH, System.DateTime endH, long StaffID) {
            return base.Channel.SubmitHolidayReq(startH, endH, StaffID);
        }
        
        public System.Threading.Tasks.Task<bool> SubmitHolidayReqAsync(System.DateTime startH, System.DateTime endH, long StaffID) {
            return base.Channel.SubmitHolidayReqAsync(startH, endH, StaffID);
        }
    }
}
